<?php
//# some settings have to be editied manually in this file, some settings can be set via web gui
//# PS: why this strange format? this config file might contain sensitive values like admin's e-mail and hence should NEVER be visible to the public
// path2data						= ./data # where to find the data in the format shelly-2024-01-05.log generated by shelly.sh
// refresh_auto					    = 5 # refresh automatically with same parameter every 5min
// auto_reload_string				= on # default
?>